language: go
sudo: false
go:
  - 1.10.3

notifications:
  email: false

install:
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/bosun.org/
  - export GOPATH=$HOME/gopath #Fix gopath. Original has trailing :
  - chmod +x $GOPATH/src/bosun.org/build/validate.sh
  - go get github.com/captncraig/setStatus
  - npm i -g typescript@2.4.2

script: $GOPATH/src/bosun.org/build/validate.sh
